# 解析器初始化参数
# 格式 key=value

# 脚本执行包装器
executor_core="file:///android_asset/kr-script/executor.sh"

# 工具目录
toolkit_dir="file:///android_asset/kr-script/toolkit"

# 启动时执行的脚本
before_start_sh="file:///android_asset/kr-script-online/before_start.sh"

# 页面配置文件
page_list_config_sh="file:///android_asset/kr-script-online/more.sh, file:///android_asset/kr-script-online/favorites.sh"
